### ISSUE TITLE
Queries return max of 20 records - possible to disable?

### ISSUE THREAD

**Issue by chhhris** [basecrm/basecrm-ruby#15]
I noticed that all my queries return a max of 20 records -- is there any way I can disable that limit?

![screen shot 2014-07-31 at 10 32 02 am](https://cloud.githubusercontent.com/assets/2659618/3768820/597b4912-18db-11e4-98e4-aae7975f356a.png)

**Comment by snario** [comment]
Any way to get all of them? Or even a count? :/

**Comment by iaintshine** [comment]
With the current client library version it's as easy as calling `cient.deals.all.each { |d| ... }`. Closing since it's related to unsupported client version.
