### ISSUE TITLE
Does Session.new return any kind of errors if there is a connection problem?

### ISSUE THREAD

**Issue by eric-norcross** [basecrm/basecrm-ruby#19]
Like if the token is rejected or the service is unreachable?

**Comment by kanerogers** [comment]
Yes, absolutely. It will fail with an Exception if it's not able to contact the API server to fetch a token.

**Comment by eric-norcross** [comment]
Perhaps I'm implementing it wrong, my setup looks like this: 

    begin
      session = BaseCrm::Session.new("abc123")
    rescue => error
      Rails.logger.debug "An error occurred: #{error}"
    else 
      Rails.logger.debug "Connected to CRM successfully"
    end

However it always hits the else as if it's connected successfully. Is there documentation for this?

**Comment by marcinbunsch** [comment]
Hi Eric,

The BaseCrm::Session initializer does not connect to Base. I prefer when initializers do not perform any breakable action. If you need to check whether the connection is ok, I recommend doing something like this:

```ruby
session = BaseCrm::Session.new("abc123")
begin
  session.account
rescue => error
  Rails.logger.debug "An error occurred: #{error}"
else 
  Rails.logger.debug "Connected to CRM successfully"
end
```

In case of an error, the base_crm gem will raise exceptions from the api_client gem, which you can find here: https://github.com/futuresimple/api_client/blob/master/lib/api_client/connection/basic.rb#L85

**Comment by kanerogers** [comment]
Oh. Yes. Right. Sorry. :-)

---
Kane RogersProduct Manager

CleanStream




t: +61 401 633 346

e: kane@cleanstream.com.au
