### ISSUE TITLE
Notes are not being paginated.

### ISSUE THREAD

**Issue by kanerogers** [basecrm/basecrm-ruby#2]
Hey, guys,

Doesn't look like notes are being paginated properly:

````ruby
irb(main):011:0> session.notes.all.count
{}
=> 20
irb(main):012:0>

**Comment by iaintshine** [comment]
With the current client library version it's as easy as calling `client.notes.all.each { |d| ... }`, so with new version we've abstracted pagination away.

**Comment by iaintshine** [comment]
Closing since it's related to unsupported client version.
