### ISSUE TITLE
Library not posting source_id when leads are created

### ISSUE THREAD

**Issue by jpatel531** [basecrm/basecrm-ruby#22]
Hi there - I don't believe the source_id is being posted to the Base v2 API. I can't find it in the `lead` model either

**Comment by itsderek23** [comment]
+1. Seeing the same behavior on update as well.

**Comment by nhoffmann** [comment]
#24

**Comment by nhoffmann** [comment]
I just ran into the same thing. The `source_id`attribute gets cleaned up during sanitization because it is not included in the `OPTS_KEYS_TO_PERSIST` set. I guess with  #24 I created a duplicate of this ticket then.

**Comment by efedasz** [comment]
Should be ok in version `1.2.3`, closing.
