### ISSUE TITLE
lead has no `persisted?` method

### ISSUE THREAD

**Issue by dangodev** [basecrm/basecrm-ruby#23]
Contrary to the [Leads](https://github.com/basecrm/basecrm-ruby/wiki/Leads) wiki, `leads.persisted?` neither returns true nor false, it seems, after calling `leads.create()`. It’s not even part of the method. The only thing that returns is:

```
BaseCRM::Lead
{
  id: [ID of created lead],
  owner_id: [ID of default owner],
  …
}
```
followed by the rest of the lead data.

I’ve been using `lead.id.present?` to validate success. Am I missing something? Or is the Wiki outdated / incorrect?

**Comment by iaintshine** [comment]
Yeah wiki was outdated and included documentation related to API v1 and v1 client which is not supported any more. I've removed misleading docs. Please use README.md as a reference.
