### ISSUE TITLE
Cannot query lead sources

### ISSUE THREAD

**Issue by nhoffmann** [basecrm/basecrm-ruby#25]
Currently, the `Sources` service only returns deal sources, but the api documentation makes a distinction between `/deal_sources` and `lead_sources` endpoints. 
So I guess the name of the service should reflect that and a new service to retrieve lead sources has to be introduced.

However, that would be a fair amount of duplication :)

Would it make sense to include a `resource_type` option to the `BaseCRM::Sources.where` method, like you do with `BaseCRM::Tags.where`? 

Since all the services are generated, I guess the change has to be made at the underlying API schema.
Happy to provide a PR, but I don't know where the schema is defined.

**Comment by efedasz** [comment]
Version 1.3.0 have introduced distinction between LeadSource and DealSource.
