### ISSUE TITLE
Cannot retrieve custom_fields from the API

### ISSUE THREAD

**Issue by nhoffmann** [basecrm/basecrm-ruby#26]
I could not find documentation on how to retrieve custom fields from the API.

This is not a problem of this client though.

**Comment by iaintshine** [comment]
Yeah, the question isn't client related but API related. I guess you meant how to retrieve custom fields definitions, and if yes than we don't support it in API v2 at the moment.

**Comment by nhoffmann** [comment]
Ok thanks. Is this planned for a later release though?
