### ISSUE TITLE
Convert lead to deal

### ISSUE THREAD

**Issue by Nowaker** [basecrm/basecrm-ruby#30]
Is there any API end-point for converting a lead to a deal? If not, consider this issue as a feature request. :-)

**Comment by iaintshine** [comment]
Hi @Nowaker,

Currently API V2 does not expose lead conversion. Please make a feature request via [official Uservoice page](https://futuresimple.uservoice.com/forums/296430-api).

**Comment by andriytkachiv** [comment]
@iaintshine Hi, this feature still does not exists and nobody cares about Uservoice. Without this feature my integration does not make any sense. WIll it be planned?

**Comment by patrick-gleeson** [comment]
FWIW API v2 now exposes lead conversions: https://developers.getbase.com/docs/rest/reference/lead_conversions
