### ISSUE TITLE
How do I set a custom field?

### ISSUE THREAD

**Issue by russellsilva** [basecrm/basecrm-ruby#41]
I can't figure out how to set a custom field. Here's my code snippet so far:

```
token = "redacted"
client = BaseCRM::Client.new(access_token: token)
client.leads.create(first_name: "Test", last_name: "Test")
```

There's a custom field in my Base setup named `Notes`. How do I update the custom field and save the change to Base?

**Comment by jdabrowa** [comment]
Hi, you simply need to specify a `custom_fields` hash with a `Note` key:

```
token = "redacted"
client = BaseCRM::Client.new(access_token: token)
client.leads.create(first_name: "Test", last_name: "Test", custom_fields: {"Notes" => "This is a note"})
```

(I realize this was a long time ago, answering for future reference).
